apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-raw-folder
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: airflow
    name: airflow-local-raw-folder
  hostPath:
    path: "/host/data/src/raw/silver/"
