apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: airflow
    name: models-storage-pvc
  hostPath:
    path: "/host/kubernetes/mlflow/models"
